version: '2.1'

services:
    web:
        build: .
        env_file:
            - .env
        command: pipenv run gunicorn --bind 0.0.0.0:8700 --timeout 300 --certfile=nginx/certs/sczgendev.crt --keyfile=nginx/certs/sczgendev.key SzGen.wsgi:application
        ports:
            - "8700:8700"
        expose:
            - "8700"
        volumes:
            - static_volume:/code/szgenapp/static
            - media_volume:/code/szgenapp/media
            - log_volume:/code/logs
            - db_volume:/code/data

    nginx:
        build: ./nginx
        ports:
            - "443:443"
        depends_on:
            - web
        volumes:
            - static_volume:/code/szgenapp/static
            - media_volume:/code/szgenapp/media

volumes:
    db_volume:
    static_volume:
    media_volume:
    log_volume:
