# Generated by Django 2.2.3 on 2019-07-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60)),
                ('precursor', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('STUDY_COMPLETED', 'Completed'), ('STUDY_ONGOING', 'Ongoing'), ('STUDY_NOTFUNDED', 'Not funded'), ('STUDY_OMIT', 'Omit')], max_length=20)),
            ],
            options={
                'verbose_name': 'Study',
                'verbose_name_plural': 'Studies',
                'ordering': ('precursor',),
            },
        ),
    ]
