# Generated by Django 2.2.3 on 2019-07-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szgenapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
