# Generated by Django 2.2.5 on 2019-09-17 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('szgenapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='sample_types',
            field=models.ManyToManyField(blank=True, help_text='Type of sample', null=True, to='szgenapp.SampleType'),
        ),
        migrations.AlterField(
            model_name='studyparticipant',
            name='related_participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_participants', to='szgenapp.StudyParticipant'),
        ),
    ]
