# Generated by Django 2.2.5 on 2019-10-05 20:29

from django.db import migrations
from szgenapp.models.participants import COUNTRY_CHOICES, Country

def load_countries(apps, schema_editor):
    """
    Import country data
    :param apps:
    :param schema_editor:
    :return:
    """
    for country in COUNTRY_CHOICES:
        Country.objects.create(code=country[0], name=country[1])


class Migration(migrations.Migration):

    dependencies = [
        ('szgenapp', '0002_country_status'),
    ]

    operations = [
        migrations.RunPython(load_countries)
    ]


