# Generated by Django 2.2.5 on 2019-09-23 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('szgenapp', '0002_auto_20190923_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetfile',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_files', to='szgenapp.Dataset'),
        ),
        migrations.AlterField(
            model_name='datasetrow',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_participants', to='szgenapp.Dataset'),
        ),
        migrations.AlterField(
            model_name='harvestsample',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest', to='szgenapp.Sample'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='szgenapp.Sample'),
        ),
        migrations.AlterField(
            model_name='transformsample',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transform', to='szgenapp.Sample'),
        ),
    ]
