# Generated by Django 2.2.3 on 2019-09-07 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szgenapp', '0002_auto_20190907_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doctype',
            field=models.CharField(default='csv', max_length=10, verbose_name='Doctype'),
            preserve_default=False,
        ),
    ]
