# Generated by Django 2.2.5 on 2019-09-20 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szgenapp', '0002_auto_20190917_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='sample_types',
            field=models.ManyToManyField(help_text='Type of sample', to='szgenapp.SampleType'),
        ),
        migrations.AlterField(
            model_name='studyparticipant',
            name='accessid',
            field=models.CharField(blank=True, help_text='ID from Samples Access DB', max_length=30, null=True, verbose_name='AccessDB ID'),
        ),
        migrations.AlterField(
            model_name='studyparticipant',
            name='country',
            field=models.CharField(choices=[('AUS', 'Australia'), ('FIJ', 'Fiji'), ('IND', 'India'), ('MAL', 'Malaysia'), ('UNK', 'Unknown')], help_text='Participant Country', max_length=30),
        ),
        migrations.RemoveField(
            model_name='studyparticipant',
            name='related_participant',
        ),
        migrations.AddField(
            model_name='studyparticipant',
            name='related_participant',
            field=models.ManyToManyField(related_name='_studyparticipant_related_participant_+', to='szgenapp.StudyParticipant'),
        ),
        migrations.AlterField(
            model_name='studyparticipant',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('WITHDRAWN', 'Withdrawn'), ('DECEASED', 'Deceased'), ('UNKNOWN', 'Unknown')], default='ACTIVE', help_text='Participant status', max_length=20),
        ),
    ]
