# Generated by Django 2.2.5 on 2019-10-05 20:55

from django.db import migrations
from szgenapp.models.participants import Status, PARTICIPANT_STATUS_CHOICES
def load_status(apps, schema_editor):
    """
    Import country data
    :param apps:
    :param schema_editor:
    :return:
    """
    for item in PARTICIPANT_STATUS_CHOICES:
        Status.objects.create(code=item[0], name=item[1])

class Migration(migrations.Migration):

    dependencies = [
        ('szgenapp', '0003_auto_20191006_0629'),
    ]

    operations = [
        migrations.RunPython(load_status)
    ]
