# Generated by Django 2.2.3 on 2019-09-07 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('szgenapp', '0003_document_doctype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='archive',
        ),
        migrations.RemoveField(
            model_name='document',
            name='order',
        ),
        migrations.AddField(
            model_name='document',
            name='study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='szgenapp.Study'),
        ),
    ]
