# Generated by Django 2.2.3 on 2019-07-15 11:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('szgenapp', '0004_auto_20190714_2141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name': 'Participant', 'verbose_name_plural': 'Participants'},
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='secondary',
            new_name='secondaryid',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='arrival_date',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='district',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='family',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='fullnumber',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='individual',
        ),
        migrations.AlterField(
            model_name='participant',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('WITHDRAWN', 'Withdrawn'), ('DECEASED', 'Deceased'), ('UNKNOWN', 'Unknown')], default='CURRENT', max_length=20),
        ),
        migrations.RemoveField(
            model_name='participant',
            name='study',
        ),
        migrations.CreateModel(
            name='StudyParticipant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullnumber', models.CharField(blank=True, help_text='Provide full number if it cannot be generated from parts', max_length=30)),
                ('district', models.CharField(blank=True, help_text='For CBZ study enter district(1-5)', max_length=5)),
                ('family', models.CharField(blank=True, help_text='Family number if available', max_length=20)),
                ('individual', models.CharField(blank=True, help_text='Individual number if available', max_length=20)),
                ('arrival_date', models.DateField(default=datetime.date.today, help_text='Date of receiving sample, default is today')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='szgenapp.Study')),
            ],
            options={
                'verbose_name': 'Study Participant',
                'verbose_name_plural': 'Study Participants',
            },
        ),
        migrations.AddField(
            model_name='participant',
            name='study',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='szgenapp.StudyParticipant'),
            preserve_default=False,
        ),
    ]
