# Generated by Django 2.2.3 on 2019-09-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szgenapp', '0004_auto_20190907_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='pedigree',
        ),
        migrations.AlterField(
            model_name='datasetfile',
            name='type',
            field=models.CharField(choices=[('CASEID', 'Case ID'), ('DIGS', 'DIGS'), ('FIGS', 'FIGS'), ('NARRATIVE', 'Narrative'), ('RECORDS', 'Medical Records'), ('CONSENSUS', 'Consensus'), ('LDPS', 'LDPS')], help_text='Type of the dataset eg, DIGS file', max_length=100),
        ),
        migrations.AlterField(
            model_name='participant',
            name='secondaryid',
            field=models.CharField(blank=True, help_text='Alternative ID eg, ID from Samples Access DB', max_length=30, verbose_name='Secondary ID'),
        ),
        migrations.DeleteModel(
            name='ClinicalTest',
        ),
    ]
