# Generated by Django 2.2.5 on 2019-10-05 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('szgenapp', '0004_load_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyparticipant',
            name='country',
            field=models.ForeignKey(help_text='Participant Country', null=True, on_delete=django.db.models.deletion.SET_NULL, to='szgenapp.Country'),
        ),
        migrations.AlterField(
            model_name='studyparticipant',
            name='status',
            field=models.ForeignKey(help_text='Participant Status', null=True, on_delete=django.db.models.deletion.SET_NULL, to='szgenapp.Status'),
        ),
    ]
