# Generated by Django 2.2.3 on 2019-07-20 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('szgenapp', '0005_auto_20190715_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='study',
        ),
        migrations.AddField(
            model_name='studyparticipant',
            name='participant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='studyparticipants', to='szgenapp.Participant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='alphacode',
            field=models.CharField(blank=True, help_text='Alpha code if available', max_length=30, verbose_name='Alpha Code'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='npid',
            field=models.CharField(blank=True, help_text='NP ID if available', max_length=30, verbose_name='NeuroPsychiatric ID'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='secondaryid',
            field=models.CharField(blank=True, help_text='Alternative or additional ID if available', max_length=30, verbose_name='Secondary ID'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('WITHDRAWN', 'Withdrawn'), ('DECEASED', 'Deceased'), ('UNKNOWN', 'Unknown')], default='ACTIVE', max_length=20),
        ),
    ]
