# Generated by Django 2.2.3 on 2019-09-08 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('szgenapp', '0005_auto_20190907_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='accessid',
            field=models.CharField(blank=True, help_text='Alternative ID eg, ID from Samples Access DB', max_length=30, verbose_name='AccessDB ID'),
        ),
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(help_text='Upload a document for storage and/or importing data', upload_to='', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='study',
            field=models.ForeignKey(blank=True, help_text='Select only if document is related to one particular study', null=True, on_delete=django.db.models.deletion.SET_NULL, to='szgenapp.Study'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='secondaryid',
            field=models.CharField(blank=True, help_text='Alternative or additional ID if available', max_length=30, verbose_name='Secondary ID'),
        ),
    ]
