# Generated by Django 2.2.5 on 2019-10-05 21:28

from django.db import migrations
from szgenapp.models.studies import StudyStatus, STATUS_CHOICES
def load_studystatus(apps, schema_editor):
    """
    Import country data
    :param apps:
    :param schema_editor:
    :return:
    """
    for item in STATUS_CHOICES:
        StudyStatus.objects.create(code=item[0], name=item[1])

class Migration(migrations.Migration):

    dependencies = [
        ('szgenapp', '0006_studystatus'),
    ]

    operations = [
        migrations.RunPython(load_studystatus)
    ]
