# Generated by Django 2.2.3 on 2019-09-08 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('szgenapp', '0008_auto_20190908_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinical',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_participant', to='szgenapp.StudyParticipant'),
        ),
    ]
