# Generated by Django 2.2.3 on 2019-07-20 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('szgenapp', '0008_auto_20190720_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetrow',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_participants', to='szgenapp.Dataset'),
        ),
    ]
