# Generated by Django 2.2.5 on 2019-10-05 21:52

from django.db import migrations
from szgenapp.models.samples import SAMPLE_TYPES, SampleType
def load_sampletypedescription(apps, schema_editor):
    """
    Load sampletypes from list as created in import - assumes existing or creates new
    :param apps:
    :param schema_editor:
    :return:
    """
    for item in SAMPLE_TYPES:
        sampletype = SampleType.objects.filter(name=item[1]).first()
        if sampletype:
            sampletype.description = item[2]
            sampletype.save()
        else:
            SampleType.objects.create(name=item[1], description=item[2])

class Migration(migrations.Migration):

    dependencies = [
        ('szgenapp', '0009_auto_20191006_0746'),
    ]

    operations = [
        migrations.RunPython(load_sampletypedescription)
    ]
