# Generated by Django 2.2.3 on 2019-09-08 13:07

from django.db import migrations, models
import szgenapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('szgenapp', '0010_auto_20190908_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographic',
            name='age_assessment',
            field=models.IntegerField(blank=True, help_text='Age at the time of assessment', null=True, validators=[szgenapp.validators.validate_age], verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='demographic',
            name='current_emp_status',
            field=models.CharField(blank=True, choices=[('disabled', 'Formerly worked, no longer able (disabled)'), ('homemaker', 'Homemaker primary role'), ('never worked', 'Never worked at least 30% of time'), ('student', 'Full-time student'), ('unemployed', 'Not disabled but not working (unemployed)'), ('working', 'Working at least 30% of time'), ('unknown', 'Unknown')], help_text='Employment status (at time of assessment)', max_length=30, null=True, verbose_name='Current Employment'),
        ),
        migrations.AlterField(
            model_name='demographic',
            name='employment_history',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Always worked'), (2, 'Periods of unemployment not related to illness'), (3, 'Minor occupational dysfunction'), (4, 'Moderate occupational dysfunction'), (5, 'Severe occupational dysfunction'), (0, 'Unknown')], help_text='Level of occupational disability over the past 5 years', null=True, verbose_name='Past Employment'),
        ),
        migrations.AlterField(
            model_name='demographic',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='demographic',
            name='living_arr',
            field=models.CharField(blank=True, choices=[('alone', 'Lives alone (including hostel)'), ('facility', 'Lives in a psychiatric treatment facility'), ('family', 'Lives with biological family members and/or spouse'), ('others', 'Lives with people who are not family (e.g. friends, housemates)'), ('unknown', 'Unknown')], help_text='Who the individual currently resides with (at time of assessment)', max_length=30, null=True, verbose_name='Living arrangement'),
        ),
        migrations.AlterField(
            model_name='demographic',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('married', 'Married'), ('nevmar', 'Single or Never married'), ('sepdiv', 'Separated or divorced'), ('widowed', 'Widowed, not remarried'), ('unknown', 'Unknown')], help_text='Marital status at the time of assessment', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='demographic',
            name='years_school',
            field=models.IntegerField(blank=True, help_text='Years of formal schooling', null=True, validators=[szgenapp.validators.validate_school_years]),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='age_first_treatment',
            field=models.IntegerField(blank=True, help_text='Age at which psychiatric treatment first accessed', null=True, validators=[szgenapp.validators.validate_onset_age]),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='age_onset',
            field=models.IntegerField(blank=True, help_text='Age at onset of psychosis', null=True, validators=[szgenapp.validators.validate_onset_age]),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='dup',
            field=models.IntegerField(blank=True, help_text='Period between onset and first treatment (in years)', null=True, verbose_name='Duration of Untreated Psychosis (DUP)'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='hospitalisation_number',
            field=models.IntegerField(blank=True, help_text='Number of psychiatric hospitalisations (lifetime)', null=True, validators=[szgenapp.validators.validate_number_hosp], verbose_name='Number of hospitalisations'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='illness_duration',
            field=models.IntegerField(blank=True, help_text='Illness duration (onset to current) in years', null=True, validators=[szgenapp.validators.validate_ill_duration]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='country',
            field=models.CharField(choices=[('IND', 'India'), ('AUS', 'Australia'), ('SWK', 'Sarawak')], max_length=30),
        ),
    ]
