# Generated by Django 2.2.3 on 2019-07-21 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szgenapp', '0010_auto_20190721_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetrow',
            name='consensus',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes (electronic)'), (2, 'Yes (hard copy only)'), (3, 'Yes (exists, but yet to locate)'), (9, 'Unknown')], default=9),
        ),
        migrations.AlterField(
            model_name='datasetrow',
            name='digs',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes (electronic)'), (2, 'Yes (hard copy only)'), (3, 'Yes (exists, but yet to locate)'), (9, 'Unknown')], default=9),
        ),
        migrations.AlterField(
            model_name='datasetrow',
            name='figs',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes (electronic)'), (2, 'Yes (hard copy only)'), (3, 'Yes (exists, but yet to locate)'), (9, 'Unknown')], default=9),
        ),
        migrations.AlterField(
            model_name='datasetrow',
            name='ldps',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes (electronic)'), (2, 'Yes (hard copy only)'), (3, 'Yes (exists, but yet to locate)'), (9, 'Unknown')], default=9),
        ),
        migrations.AlterField(
            model_name='datasetrow',
            name='narrative',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes (electronic)'), (2, 'Yes (hard copy only)'), (3, 'Yes (exists, but yet to locate)'), (9, 'Unknown')], default=9),
        ),
        migrations.AlterField(
            model_name='datasetrow',
            name='records',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes (electronic)'), (2, 'Yes (hard copy only)'), (3, 'Yes (exists, but yet to locate)'), (9, 'Unknown')], default=9),
        ),
    ]
