# Generated by Django 2.2.5 on 2019-10-06 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szgenapp', '0010_load_sampletype_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dsmiv',
            fields=[
                ('code', models.CharField(help_text='DSMIV code', max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='DSMIV name', max_length=30)),
            ],
            options={
                'verbose_name': 'DSMIV',
                'verbose_name_plural': 'DSMIV options',
            },
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('code', models.CharField(help_text='Employment code', max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Employment name', max_length=100)),
            ],
            options={
                'verbose_name': 'Employment',
                'verbose_name_plural': 'Employment options',
            },
        ),
        migrations.CreateModel(
            name='EmploymentHistory',
            fields=[
                ('code', models.SmallIntegerField(help_text='Employment History code', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Employment History name', max_length=100)),
            ],
            options={
                'verbose_name': 'Employment History',
                'verbose_name_plural': 'Employment History options',
            },
        ),
        migrations.CreateModel(
            name='Gaf',
            fields=[
                ('code', models.CharField(help_text='GAF code', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='GAF name', max_length=100)),
            ],
            options={
                'verbose_name': 'GAF',
                'verbose_name_plural': 'GAF options',
            },
        ),
        migrations.CreateModel(
            name='Gafwl',
            fields=[
                ('code', models.CharField(help_text='WL GAF code', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='WL GAF name', max_length=100)),
            ],
            options={
                'verbose_name': 'WL GAF',
                'verbose_name_plural': 'WL GAF options',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('code', models.CharField(help_text='Gender code', max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Gender name', max_length=30)),
            ],
            options={
                'verbose_name': 'Gender',
                'verbose_name_plural': 'Genders',
            },
        ),
        migrations.CreateModel(
            name='Illness',
            fields=[
                ('code', models.SmallIntegerField(help_text='Illness code', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Illness name', max_length=100)),
            ],
            options={
                'verbose_name': 'Illness',
                'verbose_name_plural': 'Illness options',
            },
        ),
        migrations.CreateModel(
            name='Living',
            fields=[
                ('code', models.CharField(help_text='Living code', max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Living name', max_length=100)),
            ],
            options={
                'verbose_name': 'Living',
                'verbose_name_plural': 'Living options',
            },
        ),
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('code', models.CharField(help_text='Marital Status code', max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Marital Status name', max_length=100)),
            ],
            options={
                'verbose_name': 'Marital Status',
                'verbose_name_plural': 'Marital Statuses',
            },
        ),
        migrations.CreateModel(
            name='Onset',
            fields=[
                ('code', models.CharField(help_text='Onset code', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Onset name', max_length=100)),
            ],
            options={
                'verbose_name': 'Onset',
                'verbose_name_plural': 'Onset options',
            },
        ),
        migrations.CreateModel(
            name='Religious',
            fields=[
                ('code', models.CharField(help_text='Religious code', max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Religious name', max_length=100)),
            ],
            options={
                'verbose_name': 'Religious',
                'verbose_name_plural': 'Religious options',
            },
        ),
        migrations.CreateModel(
            name='Severity',
            fields=[
                ('code', models.CharField(help_text='Severity code', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Severity name', max_length=50)),
            ],
            options={
                'verbose_name': 'Severity',
                'verbose_name_plural': 'Severity options',
            },
        ),
        migrations.CreateModel(
            name='SeverityPattern',
            fields=[
                ('code', models.SmallIntegerField(help_text='Severity Pattern code', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Severity Pattern name', max_length=100)),
            ],
            options={
                'verbose_name': 'Severity Pattern',
                'verbose_name_plural': 'Severity Pattern options',
            },
        ),
        migrations.CreateModel(
            name='SymptomPattern',
            fields=[
                ('code', models.SmallIntegerField(help_text='Symptom Pattern code', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Symptom Pattern name', max_length=100)),
            ],
            options={
                'verbose_name': 'Symptom Pattern',
                'verbose_name_plural': 'Symptom Pattern options',
            },
        ),
    ]
