# Generated by Django 2.2.3 on 2019-09-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szgenapp', '0011_auto_20190908_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetrow',
            name='consensus',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes (electronic)'), (2, 'Yes (hard copy only)'), (3, 'Yes (not located)'), (9, 'Unknown')], default=9, null=True),
        ),
        migrations.AlterField(
            model_name='datasetrow',
            name='ldps',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes (electronic)'), (2, 'Yes (hard copy only)'), (3, 'Yes (not located)'), (9, 'Unknown')], default=9, null=True),
        ),
        migrations.AlterField(
            model_name='datasetrow',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
    ]
