# Generated by Django 2.2.5 on 2019-10-06 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('szgenapp', '0012_clinical_lookups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographic',
            name='current_emp_status',
            field=models.ForeignKey(blank=True, help_text='Employment status (at time of assessment)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='szgenapp.Employment', verbose_name='Current Employment'),
        ),
        migrations.AlterField(
            model_name='demographic',
            name='employment_history',
            field=models.ForeignKey(blank=True, help_text='Level of occupational disability over the past 5 years', null=True, on_delete=django.db.models.deletion.SET_NULL, to='szgenapp.EmploymentHistory', verbose_name='Past Employment'),
        ),
        migrations.AlterField(
            model_name='demographic',
            name='gender',
            field=models.ForeignKey(blank=True, help_text='Gender of participant', null=True, on_delete=django.db.models.deletion.SET_NULL, to='szgenapp.Gender'),
        ),
        migrations.AlterField(
            model_name='demographic',
            name='living_arr',
            field=models.ForeignKey(blank=True, help_text='Who the individual currently resides with (at time of assessment)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='szgenapp.Living', verbose_name='Living arrangement'),
        ),
        migrations.AlterField(
            model_name='demographic',
            name='marital_status',
            field=models.ForeignKey(blank=True, help_text='Marital status at the time of assessment', null=True, on_delete=django.db.models.deletion.SET_NULL, to='szgenapp.MaritalStatus'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='summary',
            field=models.ForeignKey(blank=True, help_text='DSMIV Diagnosis', null=True, on_delete=django.db.models.deletion.SET_NULL, to='szgenapp.Dsmiv', verbose_name='DSMIV'),
        ),
        migrations.AlterField(
            model_name='symptomsbehaviour',
            name='affective_flattening',
            field=models.ForeignKey(blank=True, help_text='Severity of current affective flattening/inappropriate affect (past 30 days)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affective_flattening', to='szgenapp.Severity', verbose_name='Affective Flattening'),
        ),
        migrations.AlterField(
            model_name='symptomsbehaviour',
            name='allogia',
            field=models.ForeignKey(blank=True, help_text='Severity of current alogia/negative thought disorder (past 30 days)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allogia', to='szgenapp.Severity', verbose_name='Alogia'),
        ),
        migrations.AlterField(
            model_name='symptomsbehaviour',
            name='anhedonia',
            field=models.ForeignKey(blank=True, help_text='Severity of current anhedonia/asociality (past 30 days)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anhedonia', to='szgenapp.Severity', verbose_name='Anhedonia / Asociality'),
        ),
        migrations.AlterField(
            model_name='symptomsbehaviour',
            name='avolition',
            field=models.ForeignKey(blank=True, help_text='Severity of current avolition/apathy (past 30 days)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avolition', to='szgenapp.Severity', verbose_name='Avolition / Apathy'),
        ),
        migrations.AlterField(
            model_name='symptomsbehaviour',
            name='severe_disorg_catatonic_behav',
            field=models.ForeignKey(blank=True, help_text='Severity of current disorganised/catatonic behaviour (past 30 days)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='severe_disorg_catatonic_behav', to='szgenapp.Severity', verbose_name='Severity of Current Disorganised Behaviour'),
        ),
        migrations.AlterField(
            model_name='symptomsbehaviour',
            name='severe_disorg_speech',
            field=models.ForeignKey(blank=True, help_text="Severity of current disorganised speech/positive formal thought disorder (past 30 days). 'Question' category usually grouped with 'Unknown' category for analyses", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='severe_disorg_speech', to='szgenapp.Severity', verbose_name='Severity of Current Disorganised Speech'),
        ),
        migrations.AlterField(
            model_name='symptomsdelusion',
            name='sevcur_delusions',
            field=models.ForeignKey(blank=True, help_text='Severity of current delusions (past 30 days)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sevcur_delusions', to='szgenapp.Severity', verbose_name='Severity of Current Delusions'),
        ),
        migrations.AlterField(
            model_name='symptomsgeneral',
            name='curr_gaf',
            field=models.ForeignKey(blank=True, help_text='Current (past 30 days) rating on the Global Assessment of Function Scale', null=True, on_delete=django.db.models.deletion.SET_NULL, to='szgenapp.Gaf', verbose_name='Current Global Assessment of Function (GAF)'),
        ),
        migrations.AlterField(
            model_name='symptomsgeneral',
            name='illness_course',
            field=models.ForeignKey(blank=True, help_text='Categorical illness course, as defined in the DIGS', null=True, on_delete=django.db.models.deletion.SET_NULL, to='szgenapp.Illness', verbose_name='Illness Course'),
        ),
        migrations.AlterField(
            model_name='symptomsgeneral',
            name='onset',
            field=models.ForeignKey(blank=True, help_text='Rapidity of prodromal period (between noticeable social/occupational decline and definite onset of psychosis)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='szgenapp.Onset', verbose_name='Onset of Psychosis'),
        ),
        migrations.AlterField(
            model_name='symptomsgeneral',
            name='severity_pattern',
            field=models.ForeignKey(blank=True, help_text='Pattern of severity of decline in functioning over the course of the illness, as defined in the DIGS', null=True, on_delete=django.db.models.deletion.SET_NULL, to='szgenapp.SeverityPattern', verbose_name='Severity Pattern'),
        ),
        migrations.AlterField(
            model_name='symptomsgeneral',
            name='symptom_pattern',
            field=models.ForeignKey(blank=True, help_text='Relationship between positive and negative symptoms throughout the course of the illness, as defined in the DIGS', null=True, on_delete=django.db.models.deletion.SET_NULL, to='szgenapp.SymptomPattern', verbose_name='Symptom Pattern'),
        ),
        migrations.AlterField(
            model_name='symptomsgeneral',
            name='wl_gaf',
            field=models.ForeignKey(blank=True, help_text='Lowest (lifetime) rating on the Global Assessment of Function Scale', null=True, on_delete=django.db.models.deletion.SET_NULL, to='szgenapp.Gafwl', verbose_name='Worst Lifetime Global Assessment of Function (GAF)'),
        ),
        migrations.AlterField(
            model_name='symptomshallucination',
            name='severe_hallucinations',
            field=models.ForeignKey(blank=True, help_text="Severity of current hallucinations (past 30 days). 'Question' category usually grouped with 'Unknown' category for analyses", null=True, on_delete=django.db.models.deletion.SET_NULL, to='szgenapp.Severity', verbose_name='Severity of Current Hallucinations'),
        ),
        migrations.AlterField(
            model_name='symptomsdelusion',
            name='religious_delusions',
            field=models.ForeignKey(blank=True,
                                    help_text='Presence (lifetime) of religious delusions or delusions of magic',
                                    null=True, on_delete=django.db.models.deletion.SET_NULL, to='szgenapp.Religious',
                                    verbose_name='Religious / Magic Delusions'),
        ),
    ]
