# Generated by Django 2.2.3 on 2019-07-21 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('szgenapp', '0012_auto_20190721_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='stage',
        ),
    ]
