# Generated by Django 2.2.3 on 2019-07-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szgenapp', '0013_remove_sample_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvestsample',
            name='harvest_date',
            field=models.DateField(blank=True, verbose_name='Harvest Date'),
        ),
        migrations.AlterField(
            model_name='harvestsample',
            name='regrow_date',
            field=models.DateField(blank=True, verbose_name='Regrow Date'),
        ),
        migrations.AlterField(
            model_name='subsample',
            name='extraction_date',
            field=models.DateField(blank=True, help_text='Date of DNA Extraction', verbose_name='Extraction Date'),
        ),
        migrations.AlterField(
            model_name='subsample',
            name='sample_num',
            field=models.IntegerField(default=1, help_text='For example, number 1 of 5 subsamples'),
        ),
        migrations.AlterField(
            model_name='subsample',
            name='storage_date',
            field=models.DateField(blank=True, verbose_name='Storage Date'),
        ),
        migrations.AlterField(
            model_name='subsample',
            name='used_date',
            field=models.DateField(blank=True, verbose_name='Used Date'),
        ),
        migrations.AlterField(
            model_name='transformsample',
            name='transform_date',
            field=models.DateField(blank=True, verbose_name='Transform Date'),
        ),
    ]
