# Generated by Django 2.2.5 on 2020-04-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szgenapp', '0013_clinical_field_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='sample_location',
            field=models.CharField(blank=True, help_text='Location of sample as free text', max_length=60, null=True, verbose_name='Location'),
        ),
    ]
