# Generated by Django 2.2.3 on 2019-07-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szgenapp', '0014_auto_20190721_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsample',
            name='extraction_date',
            field=models.DateField(blank=True, help_text='Date of DNA Extraction', null=True, verbose_name='Extraction Date'),
        ),
    ]
