# Generated by Django 2.2.5 on 2020-04-05 07:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('szgenapp', '0015_wiki'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wiki',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
