# Generated by Django 2.2.3 on 2019-07-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szgenapp', '0015_auto_20190721_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyparticipant',
            name='fullnumber',
            field=models.CharField(blank=True, help_text='Provide full number if it cannot be generated from parts', max_length=30, verbose_name='Full Number'),
        ),
        migrations.AlterField(
            model_name='subsample',
            name='storage_date',
            field=models.DateField(blank=True, help_text='Date stored', null=True, verbose_name='Storage Date'),
        ),
        migrations.AlterField(
            model_name='subsample',
            name='used_date',
            field=models.DateField(blank=True, help_text='Date sample used', null=True, verbose_name='Used Date'),
        ),
    ]
