# Generated by Django 2.2.5 on 2020-04-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szgenapp', '0016_auto_20200405_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='help',
            field=models.BooleanField(default=False, help_text='Check box to display on Custom Help Pages', verbose_name='Link to Help'),
        ),
    ]
