# Generated by Django 2.2.3 on 2019-07-28 03:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szgenapp', '0019_auto_20190728_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyparticipant',
            name='arrival_date',
        ),
        migrations.AddField(
            model_name='sample',
            name='arrival_date',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='Date of sample arrival', null=True, verbose_name='Arrival Date'),
        ),
    ]
