# Generated by Django 2.2.3 on 2019-07-28 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szgenapp', '0020_auto_20190728_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='num',
        ),
        migrations.AddField(
            model_name='subsample',
            name='sample_num',
            field=models.IntegerField(default=1, help_text='For example, number 1 of 5 subsamples'),
        ),
    ]
