# Generated by Django 2.2.3 on 2019-07-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szgenapp', '0021_auto_20190728_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='rutgers',
        ),
        migrations.AlterField(
            model_name='shipment',
            name='rutgers_number',
            field=models.CharField(blank=True, help_text='Rutgers Shipment for LCLs', max_length=60),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipment_date',
            field=models.DateField(help_text='Date on which sample shipped', verbose_name='Shipment Date'),
        ),
    ]
