# Generated by Django 2.2.3 on 2019-08-14 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szgenapp', '0022_auto_20190728_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='country',
            field=models.CharField(choices=[('INDIA', 'India'), ('AUSTRALIA', 'Australia'), ('SARAWAK', 'Sarawak')], max_length=30),
        ),
        migrations.AlterField(
            model_name='qc',
            name='passed',
            field=models.BooleanField(default=False, help_text='True if passed QC'),
        ),
    ]
