# Generated by Django 2.2.3 on 2019-08-14 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('szgenapp', '0024_clinical_demographic_diagnosis_medicalhistory_symptomsbehaviour_symptomsdelusion_symptomsdepression_'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinical',
            name='demographic',
        ),
        migrations.RemoveField(
            model_name='clinical',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='clinical',
            name='medical',
        ),
        migrations.RemoveField(
            model_name='clinical',
            name='symptoms_behaviour',
        ),
        migrations.RemoveField(
            model_name='clinical',
            name='symptoms_delusion',
        ),
        migrations.RemoveField(
            model_name='clinical',
            name='symptoms_depression',
        ),
        migrations.RemoveField(
            model_name='clinical',
            name='symptoms_general',
        ),
        migrations.RemoveField(
            model_name='clinical',
            name='symptoms_hallucination',
        ),
        migrations.AddField(
            model_name='demographic',
            name='participant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='demo_participants', to='szgenapp.Clinical'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='participant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_participants', to='szgenapp.Clinical'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='participant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mh_participants', to='szgenapp.Clinical'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='symptomsbehaviour',
            name='participant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sb_participants', to='szgenapp.Clinical'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='symptomsdelusion',
            name='participant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sd_participants', to='szgenapp.Clinical'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='symptomsdepression',
            name='participant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sm_participants', to='szgenapp.Clinical'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='symptomsgeneral',
            name='participant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sg_participants', to='szgenapp.Clinical'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='symptomshallucination',
            name='participant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sh_participants', to='szgenapp.Clinical'),
            preserve_default=False,
        ),
    ]
