# Generated by Django 2.2.3 on 2019-08-14 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('szgenapp', '0025_auto_20190814_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographic',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demographic', to='szgenapp.Clinical'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='szgenapp.Clinical'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical', to='szgenapp.Clinical'),
        ),
        migrations.AlterField(
            model_name='symptomsbehaviour',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms_behaviour', to='szgenapp.Clinical'),
        ),
        migrations.AlterField(
            model_name='symptomsdelusion',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms_delusion', to='szgenapp.Clinical'),
        ),
        migrations.AlterField(
            model_name='symptomsdepression',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms_depression', to='szgenapp.Clinical'),
        ),
        migrations.AlterField(
            model_name='symptomsgeneral',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms_general', to='szgenapp.Clinical'),
        ),
        migrations.AlterField(
            model_name='symptomshallucination',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms_hallucination', to='szgenapp.Clinical'),
        ),
    ]
