# Generated by Django 2.2.3 on 2019-08-14 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('szgenapp', '0026_auto_20190814_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinical',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical', to='szgenapp.StudyParticipant'),
        ),
        migrations.AlterField(
            model_name='demographic',
            name='current_emp_status',
            field=models.CharField(choices=[('disabled', 'Formerly worked, no longer able (disabled)'), ('homemaker', 'Homemaker primary role'), ('never worked', 'Never worked at least 30% of time'), ('student', 'Full-time student'), ('unemployed', 'Not disabled but not working (unemployed)'), ('working', 'Working at least 30% of time'), ('unknown', 'Unknown')], help_text='Employment status (at time of assessment)', max_length=30),
        ),
        migrations.AlterField(
            model_name='demographic',
            name='employment_history',
            field=models.SmallIntegerField(choices=[(1, 'Always worked'), (2, 'Periods of unemployment not related to illness'), (3, 'Minor occupational dysfunction'), (4, 'Moderate occupational dysfunction'), (5, 'Severe occupational dysfunction'), (0, 'Unknown')], help_text='Level of occupational disability over the past 5 years'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='dup_approx',
            field=models.BooleanField(default=False, help_text='Period for DUP is approximate (eg 20+)'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='hospitalisation_number_approx',
            field=models.BooleanField(default=False, help_text='Number of hospitalisations is approximate (eg >5)'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='illness_duration_approx',
            field=models.BooleanField(default=False, help_text='Period for illness duration is approximate (eg 20+)'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='other_drug_type',
            field=models.TextField(blank=True, help_text="Types of illicit drugs for which the individual meets the DSMIV criteria for lifetime abuse and/or dependence. Blank for all individuals where OthDrug is not 'Yes'", null=True, verbose_name='Illicit Drug Use Disorder Type'),
        ),
        migrations.AlterField(
            model_name='symptomsgeneral',
            name='curr_gaf',
            field=models.CharField(blank=True, choices=[('None', '81-100 (None)'), ('Mild', '61-80 (Mild)'), ('Moderate', '31-60 (Moderate)'), ('Severe', '1-30 (Severe)'), ('Unknown', 'Unknown')], help_text='Current (past 30 days) rating on the Global Assessment of Function Scale', max_length=20, null=True, verbose_name='Current Global Assessment of Function'),
        ),
        migrations.AlterField(
            model_name='symptomsgeneral',
            name='illness_course',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Episodic with interepisode residual symptoms'), (2, 'Episodic with no interepisode residual symptoms'), (3, 'Continuous'), (4, 'Single episode in partial remission'), (5, 'Single episode in full remission'), (6, 'Other, unspecified, unknown course')], help_text='Categorical illness course, as defined in the DIGS', null=True, verbose_name='Illness Course'),
        ),
        migrations.AlterField(
            model_name='symptomsgeneral',
            name='severity_pattern',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Episodic shift (no deterioration when not actively unwell)'), (2, 'Mild deterioration'), (3, 'Moderate deterioration'), (4, 'Severe deterioration'), (0, 'Unknown')], help_text='Pattern of severity of decline in functioning over the course of the illness, as defined in the DIGS', null=True, verbose_name='Severity Pattern'),
        ),
        migrations.AlterField(
            model_name='symptomsgeneral',
            name='symptom_pattern',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Continuously positive'), (2, 'Predominantly negative'), (3, 'Positive converting to negative'), (4, 'Negative converting to positive (0 observations coded "4")'), (5, 'Continuous mixture of positive and negative symptoms'), (0, 'Unknown')], help_text='Relationship between positive and negative symptoms throughout the course of the illness, as defined in the DIGS', null=True, verbose_name='Symptom Pattern'),
        ),
        migrations.AlterField(
            model_name='symptomsgeneral',
            name='wl_gaf',
            field=models.CharField(blank=True, choices=[('None', '81-100 (None)'), ('Mild', '61-80 (Mild)'), ('Moderate', '31-60 (Moderate)'), ('Severe', '1-30 (Severe)'), ('Unknown', 'Unknown')], help_text='Lowest (lifetime) rating on the Global Assessment of Function Scale', max_length=20, null=True, verbose_name='Worst Lifetime Global Assessment of Function'),
        ),
    ]
