# Generated by Django 2.2.3 on 2019-08-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szgenapp', '0027_auto_20190814_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptomsbehaviour',
            name='affective_flattening',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Question', 'Question'), ('Mild', 'Mild'), ('Moderate', 'Moderate'), ('Marked', 'Marked'), ('Severe', 'Severe'), ('Unknown', 'Unknown')], help_text='Severity of current affective flattening/inappropriate affect (past 30 days)', max_length=20, null=True, verbose_name='Affective Flattening'),
        ),
    ]
