# Generated by Django 2.2.3 on 2019-08-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szgenapp', '0028_auto_20190814_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='illness_duration_approx',
            field=models.NullBooleanField(default=False, help_text='Period for illness duration is approximate (eg 20+)'),
        ),
    ]
