# Generated by Django 2.2.3 on 2019-08-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szgenapp', '0029_auto_20190814_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='hospitalisation',
            field=models.NullBooleanField(help_text='Whether the individual has ever been hospitalised for psychiatric reasons'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='illness_duration_approx',
            field=models.BooleanField(default=False, help_text='Period for illness duration is approximate (eg 20+)'),
        ),
    ]
