# Generated by Django 2.2.3 on 2019-08-17 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('szgenapp', '0030_auto_20190814_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demographic',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='symptomsbehaviour',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='symptomsdelusion',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='symptomsdepression',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='symptomsgeneral',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='symptomshallucination',
            name='participant',
        ),
        migrations.AddField(
            model_name='clinical',
            name='demographic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clinical_demographic', to='szgenapp.Demographic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinical',
            name='diagnosis',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clinical_diagnosis', to='szgenapp.Diagnosis'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinical',
            name='medical',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clinical_medical', to='szgenapp.MedicalHistory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinical',
            name='symptoms_behaviour',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clinical_behaviour', to='szgenapp.SymptomsBehaviour'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinical',
            name='symptoms_delusion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clinical_delusion', to='szgenapp.SymptomsDelusion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinical',
            name='symptoms_depression',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clinical_depression', to='szgenapp.SymptomsDepression'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinical',
            name='symptoms_general',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clinical_general', to='szgenapp.SymptomsGeneral'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinical',
            name='symptoms_hallucination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clinical_hallucination', to='szgenapp.SymptomsHallucination'),
            preserve_default=False,
        ),
    ]
