# Generated by Django 2.2.3 on 2019-08-18 08:26

from django.db import migrations, models
import django.db.models.deletion
import szgenapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('szgenapp', '0032_auto_20190817_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomsMania',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('final_mania', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Unk', 'Unknown')], help_text='Definite (lifetime) presence of at least one DSMIV manic episode', max_length=10, null=True, verbose_name='Final mania')),
                ('elevated_mood', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Unk', 'Unknown')], help_text='Elated mood for 1+ week (or any duration if hospitalised) (either elated or irritable mood must be present for a DSMIV manic episode)', max_length=10, null=True, verbose_name='Elevated/Elated mood')),
                ('irritable_mood', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Unk', 'Unknown')], help_text='Irritable mood for 1+ week (or any duration if hospitalised) (either elated or irritable mood must be present for a DSMIV manic episode)', max_length=10, null=True, verbose_name='Irritable mood')),
                ('grandiosity', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Unk', 'Unknown')], help_text='Grandiosity/inflated self esteem (DSMIV manic symptom)', max_length=10, null=True, verbose_name='Grandiosity')),
                ('decreased_sleep', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Unk', 'Unknown')], help_text='Decreased need for sleep – feels rested on little or no sleep (DSMIV manic symptom)', max_length=10, null=True, verbose_name='Decreased Need for Sleep')),
                ('pressured_speech', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Unk', 'Unknown')], help_text='More talkative or pressured speech (DSMIV manic symptom)', max_length=10, null=True, verbose_name='Pressured Speech')),
                ('racing_thoughts', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Unk', 'Unknown')], help_text='Flight of ideas or subjective racing thoughts (DSMIV manic symptom)', max_length=10, null=True, verbose_name='Racing Thoughts/Flight of Ideas')),
                ('distractibility', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Unk', 'Unknown')], help_text='Distractibility (DSMIV manic symptom)', max_length=10, null=True, verbose_name='Distractibility')),
                ('psychmotor_agitation', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Unk', 'Unknown')], help_text='Increased goal-oriented activity or psychomotor agitation (DSMIV manic symptom)', max_length=10, null=True, verbose_name='Psychomotor Agitation')),
                ('risky_behaviour', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Unk', 'Unknown')], help_text='Excessive risky pleasurable behaviour (DSMIV manic symptom)', max_length=10, null=True, verbose_name='Risky Behaviour')),
                ('manic_count', models.IntegerField(blank=True, help_text='Count of DSMIV manic symptoms used to establish the presence/absence of an episode (0-7); Symptoms are operationalised to correspond with the DSMIV diagnostic criteria. 3+ required (if elevated mood is present), 4+ required (if only irritable mood is present). One of elevated or irritable mood is essential for a manic episode (note: the presence of symptoms concurrently does not guarantee a positive rating for an episode due to time criterion).', null=True, validators=[szgenapp.validators.validate_manic_count], verbose_name='Count of Manic Symptoms')),
            ],
        ),
        migrations.RemoveField(
            model_name='symptomsdepression',
            name='decreased_sleep',
        ),
        migrations.RemoveField(
            model_name='symptomsdepression',
            name='distractibility',
        ),
        migrations.RemoveField(
            model_name='symptomsdepression',
            name='elevated_mood',
        ),
        migrations.RemoveField(
            model_name='symptomsdepression',
            name='final_mania',
        ),
        migrations.RemoveField(
            model_name='symptomsdepression',
            name='grandiosity',
        ),
        migrations.RemoveField(
            model_name='symptomsdepression',
            name='irritable_mood',
        ),
        migrations.RemoveField(
            model_name='symptomsdepression',
            name='manic_count',
        ),
        migrations.RemoveField(
            model_name='symptomsdepression',
            name='pressured_speech',
        ),
        migrations.RemoveField(
            model_name='symptomsdepression',
            name='psychmotor_agitation',
        ),
        migrations.RemoveField(
            model_name='symptomsdepression',
            name='racing_thoughts',
        ),
        migrations.RemoveField(
            model_name='symptomsdepression',
            name='risky_behaviour',
        ),
        migrations.AlterField(
            model_name='demographic',
            name='age_assessment',
            field=models.IntegerField(help_text='Age at the time of assessment', validators=[szgenapp.validators.validate_age], verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='demographic',
            name='current_emp_status',
            field=models.CharField(choices=[('disabled', 'Formerly worked, no longer able (disabled)'), ('homemaker', 'Homemaker primary role'), ('never worked', 'Never worked at least 30% of time'), ('student', 'Full-time student'), ('unemployed', 'Not disabled but not working (unemployed)'), ('working', 'Working at least 30% of time'), ('unknown', 'Unknown')], help_text='Employment status (at time of assessment)', max_length=30, verbose_name='Current Employment'),
        ),
        migrations.AlterField(
            model_name='demographic',
            name='employment_history',
            field=models.SmallIntegerField(choices=[(1, 'Always worked'), (2, 'Periods of unemployment not related to illness'), (3, 'Minor occupational dysfunction'), (4, 'Moderate occupational dysfunction'), (5, 'Severe occupational dysfunction'), (0, 'Unknown')], help_text='Level of occupational disability over the past 5 years', verbose_name='Past Employment'),
        ),
        migrations.AlterField(
            model_name='demographic',
            name='living_arr',
            field=models.CharField(choices=[('alone', 'Lives alone (including hostel)'), ('facility', 'Lives in a psychiatric treatment facility'), ('family', 'Lives with biological family members and/or spouse'), ('others', 'Lives with people who are not family (e.g. friends, housemates)'), ('unknown', 'Unknown')], help_text='Who the individual currently resides with (at time of assessment)', max_length=30, verbose_name='Living arrangement'),
        ),
        migrations.AlterField(
            model_name='symptomsdelusion',
            name='biw_delusions',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Unk', 'Unknown')], help_text='Presence (lifetime) of thought broadcast/insertion/withdrawal delusions', max_length=10, null=True, verbose_name='Broadcast /Insertion/ Withdrawal Delusions'),
        ),
        migrations.AlterField(
            model_name='symptomsdelusion',
            name='grandiose_delusions',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Unk', 'Unknown')], help_text='Presence (lifetime) of grandiose delusions', max_length=10, null=True, verbose_name='Grandiose Delusions'),
        ),
        migrations.AlterField(
            model_name='symptomsdelusion',
            name='reference_delusions',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Unk', 'Unknown')], help_text='Presence (lifetime) of delusions of reference', max_length=10, null=True, verbose_name='Referential Delusions'),
        ),
        migrations.AlterField(
            model_name='symptomsdelusion',
            name='religious_delusions',
            field=models.CharField(blank=True, choices=[('NO', 'No'), ('YES', 'Yes'), ('CUL', 'Culturally acceptable (non-delusional) beliefs'), ('U', 'Unknown')], help_text='Presence (lifetime) of religious delusions or delusions of magic', max_length=20, null=True, verbose_name='Religious /Magic Delusions'),
        ),
        migrations.AlterField(
            model_name='symptomsgeneral',
            name='curr_gaf',
            field=models.CharField(blank=True, choices=[('None', '81-100 (None)'), ('Mild', '61-80 (Mild)'), ('Moderate', '31-60 (Moderate)'), ('Severe', '1-30 (Severe)'), ('Unknown', 'Unknown')], help_text='Current (past 30 days) rating on the Global Assessment of Function Scale', max_length=20, null=True, verbose_name='Current Global Assessment of Function (GAF)'),
        ),
        migrations.AlterField(
            model_name='symptomsgeneral',
            name='wl_gaf',
            field=models.CharField(blank=True, choices=[('None', '81-100 (None)'), ('Mild', '61-80 (Mild)'), ('Moderate', '31-60 (Moderate)'), ('Severe', '1-30 (Severe)'), ('Unknown', 'Unknown')], help_text='Lowest (lifetime) rating on the Global Assessment of Function Scale', max_length=20, null=True, verbose_name='Worst Lifetime Global Assessment of Function (GAF)'),
        ),
        # migrations.AddField(
        #     model_name='clinical',
        #     name='symptoms_mania',
        #     field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clinical_mania', to='szgenapp.SymptomsMania'),
        #     preserve_default=False,
        # ),
    ]
