# Generated by Django 2.2.3 on 2019-08-18 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('szgenapp', '0033_auto_20190818_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinical',
            name='symptoms_mania',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clinical_mania', to='szgenapp.SymptomsMania'),
            preserve_default=False,
        ),
    ]
